spring:
  main:
    banner-mode: off
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5434/cashnow?schema=anime
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
server:
  error:
    include-stacktrace: on_param
